export  default  {
    FETCH_AUTH_START: 'FETCH_AUTH_START',
    FETCH_AUTH_ERROR: 'FETCH_AUTH_ERROR',
    RECEIVE_AUTH: 'RECEIVE_AUTH',
    USER_LOG_START: 'USER_LOG_START',
    USER_LOG_ERROR: 'USER_LOG_ERROR',
    USER_LOG_RECEIVE: 'USER_LOG_RECEIVE',
    USER_LOG_OUT: 'USER_LOG_OUT',
    USER_LOG_OUT_ERROR: 'USER_LOG_OUT_ERROR',
    FETCH_CONFIRM_EMAIL_START: 'FETCH_CONFIRM_EMAIL_START',
    FETCH_CONFIRM_EMAIL_ERROR: 'FETCH_CONFIRM_EMAIL_ERROR',
    CONFIRM_EMAIL_RECEIVE: 'CONFIRM_EMAIL_RECEIVE',
    CHECK_USER_IS_AUTH: 'CHECK_USER_IS_AUTH'
}